const productLinks = window.ElectronyConfig.productLinks;

window.ElectronyProducts = Object.freeze([
  Object.freeze({
    id: "electronyos",
    name: "ElectronyOS",
    category: "Software",
    eyebrow: "ELECTRONYOS",
    categoryLabel: "SMART ESTATE MANAGEMENT",
    heading: "Smart technology for modern estates and property management.",
    description: "ElectronyOS helps simplify estate operations, utilities, access and community management through one connected platform.",
    tagline: "Smart estate and utility management",
    logo: null,
    image: null,
    accentColor: "var(--color-product-electronyos)",
    landingPageUrl: productLinks.electronyos.landingPageUrl,
    appUrl: productLinks.electronyos.appUrl,
    featured: true,
    status: "live",
    ctaLabel: "Explore ElectronyOS"
  }),
  Object.freeze({
    id: "automobile",
    name: "Electrony Automobile",
    category: "Automotive",
    eyebrow: "ELECTRONY AUTOMOBILE",
    categoryLabel: "SELECTED VEHICLES",
    heading: "Selected automobiles, electric vehicles, hybrids and pickups available through Electrony.",
    description: "Explore a curated selection of vehicles and mobility products from selected automotive brands.",
    tagline: "Drive what moves you.",
    logo: null,
    image: null,
    accentColor: "#d72626",
    landingPageUrl: productLinks.automobile.landingPageUrl,
    appUrl: null,
    featured: true,
    status: "active",
    ctaLabel: "Explore Automobile"
  }),
  Object.freeze({
    id: "bills",
    name: "Electrony Bills",
    category: "Software",
    eyebrow: "ELECTRONY BILLS",
    categoryLabel: "EVERYDAY PAYMENTS",
    heading: "Everyday payments, made simpler.",
    description: "A simpler way to manage everyday digital services and payments from one place.",
    tagline: "Everyday payments, made simpler.",
    logo: null,
    image: null,
    accentColor: "var(--color-product-bills)",
    landingPageUrl: productLinks.bills.landingPageUrl,
    appUrl: productLinks.bills.appUrl,
    featured: false,
    status: "coming-soon",
    ctaLabel: "Open Bills app"
  }),
  Object.freeze({
    id: "istylist",
    name: "iStylist",
    category: "Software",
    eyebrow: "iSTYLIST",
    categoryLabel: "BEAUTY, LIFESTYLE & SERVICES",
    heading: "Where talent meets opportunity.",
    description: "A platform for beauty, lifestyle and service discovery, connecting customers with skilled providers and trusted experiences.",
    tagline: "Beauty, lifestyle and services",
    logo: null,
    image: null,
    accentColor: "var(--color-product-istylist)",
    landingPageUrl: productLinks.stylist.landingPageUrl,
    appUrl: productLinks.stylist.appUrl,
    featured: false,
    status: "live",
    ctaLabel: "Explore iStylist"
  })
]);